name: autonomy
description: "Hanya ${USER} berbagi pengalaman"
url: "https://autono.my.id"

paginate: 5
permalink: /:title
paginate_path: "/weblog/page:num/"

feed:
  path: atom.xml
  posts_limit: 2020

sass:
  style: :expanded

# Newsline True/False
newsline: false

plugins:
#  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  
feed:
  posts_limit: 100

include: ['_pages', '_includes']
